### ISSUE TITLE
Funções envolvendo saldo

### ISSUE THREAD

**Issue by GiovanniMoreira1** [Projetos-C/Projeto-4-QuemPoupaTem#7]
- [x] Criar as funções básicas do banco envolvendo saldo:
     - [x] Desenvolver a função de Depósito:
          - [x] **1. Pedir as seguintes informações para o cliente:** 
          
            - CPF do cliente
            - Valor do depósito
         
     - [x] **Desenvolver a função de Débito:**
          - [x] **1. Pedir as seguintes informações para o cliente:** 
         
            - Valor que será debitado
            - Senha            
          - [x] **2. Verificar se a senha condiz com a criada anteriormente.**

**Comment by ArturChaves** [comment]
Funcionando, só faltando aparecer no extrato
